name: bell4g_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  # Store username and password
  flutter_secure_storage: ^3.1.1
  # Show chart
  flutter_circular_chart: ^0.0.3
  # Parse HTML Pages
  html: ^0.13.3
  # Icon Pack
  font_awesome_flutter: ^7.1.0
  # RXDart to take advantage of BehaviorSubject
  rxdart: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
